### ISSUE TITLE
what is secretkey?

### ISSUE THREAD

**Issue by rcaf-anthony** [albud187/Web_App_Safety_Zone#5]
In the set on the README the admin_codes.txt file has a SECRET_KEY setting, but what this is, and how to set it is not included in the setup description.  Please include a description of this value and what/how it should be included.

![image](https://user-images.githubusercontent.com/68304791/106908808-a48d8900-66cd-11eb-9d2e-070377fcc309.png)

**Comment by albud187** [comment]
I updated the admin_codes_blank its own SECRET_KEY. It's fine for development but will need to be changed for production.

**Comment by rcaf-anthony** [comment]
It should be noted, as it could (did) confuse a new Django developer...Or removed for now and added when the app moves to production.
